import Head from 'next/head';
import Image from 'next/image';
import { Heading, Code, Link, Flex } from '@chakra-ui/react';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading textAlign="center" my={4}>
          Welcome to <a href="https://nextjs.org">Next.js! 🚀</a>
        </Heading>
      </main>

      <footer>
        <Link href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
          <Flex alignItems="center" justifyContent="center">
            <Code mr={2}>Powered by </Code>
            <span>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </Flex>
        </Link>
      </footer>
    </div>
  );
}
